language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh
    on:
      all_branches: true
      tags: true
      repo: discuss-eth/discuss-eth-contracts
  - provider: npm
    skip_cleanup: true
    email: moody.salem@gmail.com
    api_key: $NPM_KEY
    on:
      all_branches: true
      tags: true
      repo: discuss-eth/discuss-eth-contracts
notifications:
  email: true
