language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: script
  script:
    - npm run migrate:kovan
    - npm run migrate:ropsten
    - npm run migrate:rinkeby
  on:
    tags: true
    branches:
      only:
        - master