language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: script
  script: npm run migrate:kovan
  on:
    tags: true
    branches:
      only:
        - master