language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npm run migrate:kovan
    on:
      all_branches: true
      tags: true
      repo: discuss-eth/discuss.eth
  - provider: npm
    skip_cleanup: true
    email: moody.salem@gmail.com
    api_key: $NPM_KEY
    on:
      all_branches: true
      tags: true
      repo: discuss-eth/discuss.eth
notifications:
  email: true